//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssigmentGrade
    {
        public int AssigmentGradeId { get; set; }
        public string StudentName { get; set; }
        public string AssigmentName { get; set; }
        public int Grade { get; set; }
    }
}
