//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assigment
    {
        public int AssigmentId { get; set; }
        public string AssigName { get; set; }
        public string Description { get; set; }
        public System.DateTime LastDate { get; set; }
    }
}
