//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AssigmentGrade> AssigmentGrades { get; set; }
        public virtual DbSet<Assigment> Assigments { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassMaterial> ClassMaterials { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<DayDate> DayDates { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Hostel> Hostels { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<StudentAttindence> StudentAttindences { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentsGrade> StudentsGrades { get; set; }
        public virtual DbSet<StudySchedule> StudySchedules { get; set; }
        public virtual DbSet<TeacherCours> TeacherCourses { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TeacherSection> TeacherSections { get; set; }
        public virtual DbSet<MSreplication_options> MSreplication_options { get; set; }
        public virtual DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public virtual DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public virtual DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public virtual DbSet<spt_monitor> spt_monitor { get; set; }
        public virtual DbSet<Event> Events { get; set; }
    
        public virtual ObjectResult<sp_getTeacher_Result> sp_getTeacher(Nullable<int> teacherID)
        {
            var teacherIDParameter = teacherID.HasValue ?
                new ObjectParameter("TeacherID", teacherID) :
                new ObjectParameter("TeacherID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getTeacher_Result>("sp_getTeacher", teacherIDParameter);
        }
    
        public virtual int sp_MScleanupmergepublisher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MScleanupmergepublisher");
        }
    
        public virtual int sp_MSrepl_startup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSrepl_startup");
        }
    }
}
