//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentAttindences = new HashSet<StudentAttindence>();
            this.StudentsGrades = new HashSet<StudentsGrade>();
            this.StudentsGrades1 = new HashSet<StudentsGrade>();
        }
    
        public int StudentId { get; set; }
        public string StFirstName { get; set; }

        public string StAddress { get; set; }
        public Nullable<System.DateTime> StDOB { get; set; }
        public Nullable<int> StAge { get; set; }

        public string StSecondName { get; set; }
        public string StLastName { get; set; }
        public string StPassword { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public byte[] Image { get; set; }
        
        public Nullable<bool> Gender { get; set; }
        public int SectionId { get; set; }
        public string National_Number { get; set; }
        public string ImagePath { get; set; }
        public string FullName { get { return StFirstName + " " + StLastName; } set { } }
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttindence> StudentAttindences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsGrade> StudentsGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsGrade> StudentsGrades1 { get; set; }
    }
}
