//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsGrade
    {
        public int TeacherId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public int CourseId { get; set; }
        public int ClassId { get; set; }
        public int SectionId { get; set; }
        public string FirstGrade { get; set; }
        public string SecondGrade { get; set; }
        public string ThirdGrade { get; set; }
        public string FinalGrade { get; set; }
        public double Avg { get; set; }
        public int Id { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Section Section { get; set; }
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
