//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    

    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.DayDates = new HashSet<DayDate>();
            this.StudentsGrades = new HashSet<StudentsGrade>();
            this.StudySchedules = new HashSet<StudySchedule>();
            this.TeacherCourses = new HashSet<TeacherCours>();
            this.TeacherSections = new HashSet<TeacherSection>();
        }
    
        public int TeacherId { get; set; }

        public string ThFirstName { get; set; }
        public string ThAddress { get; set; }
        
        public Nullable<System.DateTime> ThHireDate { get; set; }
        public string ThDegree { get; set; }
        public string ThExperience { get; set; }

        public string ThSecondName { get; set; }

      
        public string ThLastName { get; set; }
        public string Email { get; set; }
       
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Image { get; set; }
       
        public string Password { get; set; }
    public string FullName { get { return ThFirstName + " " + ThLastName; } set { } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayDate> DayDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsGrade> StudentsGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudySchedule> StudySchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherCours> TeacherCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherSection> TeacherSections { get; set; }
    }
}
