//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherSection
    {
        public int TeacherId { get; set; }
        public int Id { get; set; }
        public int SectinId { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
